name: Generate Snake
permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Generate the snake GIF
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sarahmuthia
          outputs: dist
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-snake.svg

      # Push changes to output branch
      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Generated snake contribution grid"
          git push origin output
